# Generated by Django 5.0.1 on 2024-06-19 12:37

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0004_chatgroup_admins_chatgroup_group_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
